title: Hello, world! I'm Skyler Rydberg
description: > # this means to ignore newlines until "baseurl:"
  This is my first attempt at blogging with Jekyll and github
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Skyler Rydberg # add your name
author-img: Sky_Professional_Pic.jpg # add your photo
about-author: I'm an Electrical Engineer interested in embedded development and DSP. # add description
twitter: skyrydberg
facebook: skyrydberg
github: skyrydberg # add your Github handle
linkedin: srydberg91
email: skyrydberg@yahoo.com

# Disqus
discus-identifier: test-67iaa5dgt3 # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
